[package]
name = "ddb_convert"
version = "0.1.0"
edition = "2021"

[lib]
name = "ddb_convert"
path = "src/lib.rs"

[[bin]]
name = "ddb_convert"
path = "src/main.rs"

[dependencies]
scan_json = { path = "../../scan_json" }
rjiter = "1.2"
u8pool = "1.1"
embedded-io = "0.6"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
